INFO     - 2019-09-11 10:37:16,047 - [__main__ main 125] Output files are saved in results/MineRLTreechop-v0/dddqn\20190911T103713.281902
INFO     - 2019-09-11 10:37:16,047 - [utils log_versions 9] 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
INFO     - 2019-09-11 10:37:16,366 - [utils log_versions 10] alabaster==0.7.12,astroid==2.2.5,attrs==19.1.0,Babel==2.7.0,backcall==0.1.0,bleach==3.1.0,cached-property==1.5.1,certifi==2019.6.16,chainer==7.0.0b2,chainerrl==0.6.0,chardet==3.0.4,cloudpickle==1.2.1,colorama==0.4.1,coloredlogs==10.0,cupy-cuda100==7.0.0b2,cycler==0.10.0,decorator==4.4.0,defusedxml==0.6.0,docutils==0.15.2,entrypoints==0.3,fastrlock==0.4,filelock==3.0.12,future==0.17.1,gym==0.12.1,humanfriendly==4.18,idna==2.8,imagesize==1.1.0,ipykernel==5.1.2,ipython==7.7.0,ipython-genutils==0.2.0,isort==4.3.21,jedi==0.15.1,Jinja2==2.10.1,jsonschema==3.0.2,jupyter-client==5.3.1,jupyter-core==4.5.0,keyring==19.0.2,kiwisolver==1.1.0,lazy-object-proxy==1.4.2,lxml==4.4.1,MarkupSafe==1.1.1,matplotlib==3.0.3,mccabe==0.6.1,minerl==0.2.3,mistune==0.8.4,nbconvert==5.6.0,nbformat==4.4.0,numpy==1.17.0,numpydoc==0.9.1,opencv-python==4.1.0.25,packaging==19.1,pandocfilters==1.4.2,parso==0.5.1,pickleshare==0.7.5,pillow==6.1.0,pip==19.2.2,prompt-toolkit==2.0.9,protobuf==3.7.1,psutil==5.6.3,pycodestyle==2.5.0,pydot==1.4.1,pyflakes==2.1.1,pyglet==1.4.2,Pygments==2.4.2,pylint==2.3.1,pyparsing==2.4.2,PyQt5==5.12.3,PyQt5-sip==4.19.18,PyQtWebEngine==5.12.1,pyreadline==2.1,Pyro4==4.76,pyrsistent==0.15.4,python-dateutil==2.8.0,pytz==2019.2,pywin32-ctypes==0.2.0,pyzmq==18.1.0,QtAwesome==0.6.0,qtconsole==4.5.3,QtPy==1.9.0,requests==2.22.0,rope==0.14.0,scipy==1.3.1,serpent==1.28,setuptools==41.2.0,six==1.12.0,snowballstemmer==1.9.0,Sphinx==2.2.0,sphinxcontrib-applehelp==1.0.1,sphinxcontrib-devhelp==1.0.1,sphinxcontrib-htmlhelp==1.0.2,sphinxcontrib-jsmath==1.0.1,sphinxcontrib-qthelp==1.0.2,sphinxcontrib-serializinghtml==1.1.3,spyder==3.3.6,spyder-kernels==0.5.1,testpath==0.4.2,tornado==6.0.3,tqdm==4.34.0,traitlets==4.3.2,typed-ast==1.4.0,typing==3.6.6,typing-extensions==3.6.6,urllib3==1.25.3,wcwidth==0.1.7,webencodings==0.5.1,wheel==0.33.4,wincertstore==0.2,wrapt==1.11.2
INFO     - 2019-09-11 10:37:16,367 - [__main__ _main 137] The first `gym.make(MineRL*)` may take several minutes. Be patient!
INFO     - 2019-09-11 10:37:57,406 - [minerl.env.malmo.instance.95dbfa _launch_minecraft 635] Starting Minecraft process: ['C:\\Users\\danie\\AppData\\Local\\Temp\\tmpghn2qwmw\\Minecraft\\launchClient.bat', '-port', '9001', '-env', '-runDir', 'C:\\Users\\danie\\AppData\\Local\\Temp\\tmpghn2qwmw\\Minecraft\\run']
INFO     - 2019-09-11 10:37:57,495 - [minerl.env.malmo.instance.95dbfa _launch_process_watcher 658] Starting process watcher for process 15572 @ localhost:9001
INFO     - 2019-09-11 10:39:15,587 - [minerl.env.malmo.instance.95dbfa launch 498] Minecraft process ready
INFO     - 2019-09-11 10:39:15,590 - [__main__ wrap_env 151] Detected `gym.wrappers.TimeLimit`! Unwrap it and re-wrap our own time limit.
INFO     - 2019-09-11 10:39:15,769 - [minerl.env.malmo log_to_file 513] Logging output of Minecraft to results/MineRLTreechop-v0/dddqn\20190911T103713.281902\logs\mc_1.log
INFO     - 2019-09-11 10:39:15,848 - [env_wrappers __init__ 270] always pressing keys: ['attack']
INFO     - 2019-09-11 10:39:15,848 - [env_wrappers __init__ 276] reversed pressing keys: ['forward']
INFO     - 2019-09-11 10:39:15,848 - [env_wrappers __init__ 281] always ignored keys: ['back', 'left', 'right', 'sneak', 'sprint']
INFO     - 2019-09-11 10:39:15,849 - [env_wrappers __init__ 315] Dict(attack:Discrete(2), back:Discrete(2), camera:Box(2,), forward:Discrete(2), jump:Discrete(2), left:Discrete(2), right:Discrete(2), sneak:Discrete(2), sprint:Discrete(2)) is converted to Discrete(5).
INFO     - 2019-09-11 10:39:15,849 - [__main__ wrap_env 151] Detected `gym.wrappers.TimeLimit`! Unwrap it and re-wrap our own time limit.
INFO     - 2019-09-11 10:39:15,884 - [env_wrappers __init__ 270] always pressing keys: ['attack']
INFO     - 2019-09-11 10:39:15,885 - [env_wrappers __init__ 276] reversed pressing keys: ['forward']
INFO     - 2019-09-11 10:39:15,885 - [env_wrappers __init__ 281] always ignored keys: ['back', 'left', 'right', 'sneak', 'sprint']
INFO     - 2019-09-11 10:39:15,885 - [env_wrappers __init__ 315] Dict(attack:Discrete(2), back:Discrete(2), camera:Box(2,), forward:Discrete(2), jump:Discrete(2), left:Discrete(2), right:Discrete(2), sneak:Discrete(2), sprint:Discrete(2)) is converted to Discrete(5).
ERROR    - 2019-09-11 10:40:57,769 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\data\villages.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:40:57,898 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:40:57,898 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:40:57,898 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:40:57,898 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveLevel(WorldServer.java:1061)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:40:57,899 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:647)
ERROR    - 2019-09-11 10:40:57,900 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:149)
ERROR    - 2019-09-11 10:40:57,900 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1557)
ERROR    - 2019-09-11 10:40:57,900 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:40:57,900 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\data\capabilities.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:40:57,900 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:40:57,900 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveLevel(WorldServer.java:1061)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:647)
ERROR    - 2019-09-11 10:40:57,901 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:149)
ERROR    - 2019-09-11 10:40:57,902 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1557)
ERROR    - 2019-09-11 10:40:57,902 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:57] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:40:58,379 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM-1\data\villages_nether.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:40:58,380 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:40:58,380 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:40:58,380 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:40:58,380 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:40:58,380 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:40:58,380 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:647)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:149)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1557)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:40:58,381 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM-1\data\capabilities.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:40:58,382 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:40:58,383 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:647)
ERROR    - 2019-09-11 10:40:58,383 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:149)
ERROR    - 2019-09-11 10:40:58,383 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1557)
ERROR    - 2019-09-11 10:40:58,383 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:40:58,439 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM1\data\villages_end.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:40:58,439 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:40:58,439 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:40:58,439 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:40:58,439 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:40:58,440 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:40:58,440 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:40:58,440 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:40:58,440 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:40:58,440 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:40:58,441 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:40:58,441 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:647)
ERROR    - 2019-09-11 10:40:58,441 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:149)
ERROR    - 2019-09-11 10:40:58,441 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1557)
ERROR    - 2019-09-11 10:40:58,441 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:40:58,442 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM1\data\capabilities.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:40:58,442 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:40:58,442 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:40:58,442 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:40:58,443 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:40:58,444 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:647)
ERROR    - 2019-09-11 10:40:58,444 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:149)
ERROR    - 2019-09-11 10:40:58,444 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1557)
ERROR    - 2019-09-11 10:40:58,444 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:40:58] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:41:09,488 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\data\villages.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:41:09,488 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:41:09,488 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveLevel(WorldServer.java:1061)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:41:09,489 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:41:09,490 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:41:09,490 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:404)
ERROR    - 2019-09-11 10:41:09,490 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:328)
ERROR    - 2019-09-11 10:41:09,490 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1630)
ERROR    - 2019-09-11 10:41:09,491 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:41:09,491 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\data\capabilities.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:41:09,491 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:41:09,491 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:41:09,492 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:41:09,492 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:41:09,492 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:41:09,492 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:41:09,492 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveLevel(WorldServer.java:1061)
ERROR    - 2019-09-11 10:41:09,493 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:41:09,493 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:41:09,493 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:41:09,493 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:404)
ERROR    - 2019-09-11 10:41:09,493 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:328)
ERROR    - 2019-09-11 10:41:09,493 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1630)
ERROR    - 2019-09-11 10:41:09,494 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:41:09,544 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM-1\data\villages_nether.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:41:09,544 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:41:09,544 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:41:09,544 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:41:09,544 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:41:09,545 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:404)
ERROR    - 2019-09-11 10:41:09,546 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:328)
ERROR    - 2019-09-11 10:41:09,546 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1630)
ERROR    - 2019-09-11 10:41:09,546 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:41:09,546 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM-1\data\capabilities.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:41:09,547 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:41:09,547 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:41:09,547 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:41:09,548 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:41:09,548 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:41:09,548 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:41:09,548 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:41:09,548 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:41:09,548 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:41:09,549 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:41:09,549 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:404)
ERROR    - 2019-09-11 10:41:09,549 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:328)
ERROR    - 2019-09-11 10:41:09,549 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1630)
ERROR    - 2019-09-11 10:41:09,549 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:41:09,551 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: .\saves\TEMP_0_735327a6-dbb9-47c5-9901-af4f980a741c\DIM1\data\capabilities.dat (The system cannot find the path specified)
ERROR    - 2019-09-11 10:41:09,552 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open0(Native Method)
ERROR    - 2019-09-11 10:41:09,552 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
ERROR    - 2019-09-11 10:41:09,552 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
ERROR    - 2019-09-11 10:41:09,553 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
ERROR    - 2019-09-11 10:41:09,553 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveData(SourceFile:94)
ERROR    - 2019-09-11 10:41:09,553 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.storage.MapStorage.saveAllData(SourceFile:78)
ERROR    - 2019-09-11 10:41:09,554 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServerMulti.saveLevel(WorldServerMulti.java:56)
ERROR    - 2019-09-11 10:41:09,554 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:1008)
ERROR    - 2019-09-11 10:41:09,554 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:366)
ERROR    - 2019-09-11 10:41:09,554 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.saveAllWorlds(IntegratedServer.java:216)
ERROR    - 2019-09-11 10:41:09,554 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:404)
ERROR    - 2019-09-11 10:41:09,555 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.integrated.IntegratedServer.stopServer(IntegratedServer.java:328)
ERROR    - 2019-09-11 10:41:09,555 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1630)
ERROR    - 2019-09-11 10:41:09,555 - [minerl.env.malmo.instance.95dbfa log_to_file 535] [10:41:09] [Server thread/INFO]: [STDERR]: 	at java.lang.Thread.run(Thread.java:748)
ERROR    - 2019-09-11 10:41:11,456 - [minerl.env.core _clean_connection 448] Cleaning connection! Something must have gone wrong.
ERROR    - 2019-09-11 10:41:11,532 - [minerl.env.core step 558] Failed to take a step (timeout or error). Terminating episode and sending random observation, be aware. To account for this failure case in your code check to see if `'error' in info` where info is the info dictionary returned by the step function.
INFO     - 2019-09-11 10:41:11,780 - [chainerrl.experiments.train_agent train_agent 67] outdir:results/MineRLTreechop-v0/dddqn\20190911T103713.281902 step:1003 episode:0 R:0.0
INFO     - 2019-09-11 10:41:11,780 - [chainerrl.experiments.train_agent train_agent 68] statistics:[('average_q', -0.013503385929609181), ('average_loss', 0.012527948117728355), ('n_updates', 3)]
ERROR    - 2019-09-11 10:41:13,268 - [minerl.env.core _start_up 438] Failed to reset (socket error), trying again!
ERROR    - 2019-09-11 10:41:13,268 - [minerl.env.core _clean_connection 448] Cleaning connection! Something must have gone wrong.
ERROR    - 2019-09-11 10:41:13,268 - [minerl.env.core _clean_connection 461] Connection with Minecraft client cleaned more than once; restarting.
ERROR    - 2019-09-11 10:41:15,293 - [minerl.env.malmo _kill_minecraft_via_malmoenv 688] Attempted to send kill command to minecraft process and failed.
INFO     - 2019-09-11 10:41:15,451 - [minerl.env.malmo on_terminate 345] Minecraft process psutil.Process(pid=15572, status='terminated') terminated with exit code 15
INFO     - 2019-09-11 10:41:15,647 - [minerl.env.malmo on_terminate 345] Minecraft process psutil.Process(pid=16280, status='terminated') terminated with exit code 15
